services:
  - type: web
    name: asprogest-backend
    env: python
    plan: free
    buildCommand: "./build_backend.sh"
    startCommand: gunicorn ASPROGEST.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: asprogest
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: yes

  - type: static
    name: frontend
    buildCommand: "cd frontend && npm install && npm run build"
    staticPublishPath: "frontend/build"