services:
  - type: web
    name: asprogest-backend
    env: python
    plan: free
    buildCommand: |
      npm install --prefix frontend
      npm run build --prefix frontend
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn ASPROGEST.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: asprogest
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: yes
