services:
  - type: web
    name: asprogest-backend
    env: python
    plan: free
    buildCommand: ./build_react.sh pip install -r requirements.txt python manage.py collectstatic --noinput
    startCommand: gunicorn ASPROGEST.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: asprogest
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: RENDER
        value: yes
